---
- hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Copy the zshrc
      copy:
        src: dotfiles/zshrc
        dest: ~/.zshrc
    - name: Copy the p10k config
      copy:
        src: dotfiles/p10k.zsh
        dest: ~/.p10k.zsh
    - name: Make sure the login shell is ZSH
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
    - name: Make sure the Lite-XL directory exists
      ansible.builtin.file:
        path: ~/.config/lite-xl
        state: directory
        mode: '0755'
    - name: Copy Lite-XL config
      copy:
        src: dotfiles/init.lua
        dest: ~/.config/lite-xl/init.lua
    - name: Make sure the Lite-XL fonts directory exists
      ansible.builtin.file:
        path: ~/.config/lite-xl/fonts
        state: directory
        mode: '0755'
    - name: Download Nerd icon font for Lite-XL
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFont-Regular.ttf
        dest: ~/.config/lite-xl/fonts/icon-nerd-font.ttf
    - name: Copy pikaur config
      copy:
        src: dotfiles/pikaur.conf
        dest: ~/.config/pikaur.conf
