---
- hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Copy the zshrc
      copy:
        src: dotfiles/zshrc
        dest: ~/.zshrc
    - name: Copy the p10k config
      copy:
        src: dotfiles/p10k.zsh
        dest: ~/.p10k.zsh
    - name: Make sure the login shell is ZSH
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
    - name: Copy Lunar Vim configs
      copy:
        src: dotfiles/config.lua
        dest: ~/.config/lvim/config.lua
    - name: Copy LSP settings
      copy:
        src: dotfiles/lsp-settings
        dest: ~/.config/lvim
    - name: Copy pikaur config
      copy:
        src: dotfiles/pikaur.conf
        dest: ~/.config/pikaur.conf
