---
- hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Copy the zshrc
      copy:
        src: dotfiles/zshrc
        dest: ~/.zshrc
    - name: Copy the p10k config
      copy:
        src: dotfiles/p10k.zsh
        dest: ~/.p10k.zsh
    - name: Make sure the login shell is ZSH
      become: true
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
    - name: Make sure the Pragtical directory exists
      ansible.builtin.file:
        path: ~/.config/pragtical
        state: directory
        mode: '0755'
    - name: Copy Pragtical init
      copy:
        src: dotfiles/init.lua
        dest: ~/.config/pragtical/init.lua
    - name: Copy Pragtical config
      copy:
        src: dotfiles/user_settings.lua
        dest: ~/.config/pragtical/user_settings.lua
    - name: Make sure the Pragtical fonts directory exists
      ansible.builtin.file:
        path: ~/.config/pragtical/fonts
        state: directory
        mode: '0755'
    - name: Download Nerd icon font for Pragtical
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFont-Regular.ttf
        dest: ~/.config/pragtical/fonts/icon-nerd-font.ttf
    - name: Copy pikaur config
      copy:
        src: dotfiles/pikaur.conf
        dest: ~/.config/pikaur.conf
