---
- hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Install ZSH
      become: yes
      pacman: name=zsh state=present
    - name: Install Oh-My-ZSH 
      pacman:
        executable: pikaur
        name: oh-my-zsh-git
        state: present
    - name: Install plugins
      pacman:
        executable: pikaur
        name:
          - zsh-theme-powerlevel10k-git
          - zsh-fast-syntax-highlighting-git
          - zsh-autosuggestions
    - name: Copy the zshrc
      copy:
        src: configs/zshrc
        dest: ~/.zshrc
    - name: Copy the p10k config
      copy:
        src: configs/p10k.zsh
        dest: ~/.p10k.zsh
    - name: Change user shell to zsh 
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /bin/zsh
